{% set name = "simdjson" %}
{% set version = "3.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/simdjson/simdjson/archive/v{{ version }}.tar.gz
  sha256: ab72701b8560c4f93a5de525657b3bf34094f99a1e63bd9db3195d1bcb90aa09

build:
  number: 1
  run_exports:
    - simdjson

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  requires:
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  files:
    - test/*
  commands:
    - test -f "${PREFIX}/include/simdjson.h"                                    # [unix]
    - test -f "${PREFIX}/lib/libsimdjson${SHLIB_EXT}"                           # [unix]
    - test -f "${PREFIX}/lib/cmake/simdjson/simdjson-config.cmake"              # [unix]
    - if not exist %LIBRARY_INC%\simdjson.h (exit 1)                            # [win]
    - if not exist %LIBRARY_BIN%\simdjson.dll (exit 1)                          # [win]
    - if not exist %LIBRARY_LIB%\cmake\simdjson\simdjson-config.cmake (exit 1)  # [win]
    # Running a test trying to link to the library
    - cmake -G Ninja -S test/ -B build/ ${CMAKE_ARGS}  # [unix]
    - cmake -G Ninja -S test/ -B build/ %CMAKE_ARGS%   # [win]
    - cmake --build build/
    - cmake --build build --target test

about:
  home: https://simdjson.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Parsing gigabytes of JSON per second

  description: |
    JSON is everywhere on the Internet.
    Servers spend a *lot* of time parsing it. We need a fresh approach.
    The simdjson library uses commonly available SIMD instructions and
    microparallel algorithms to parse JSON 2.5x faster than anything else out there.
  doc_url: https://simdjson.github.io/simdjson/
  dev_url: https://github.com/simdjson/simdjson/

extra:
  recipe-maintainers:
    - JohanMabille
    - AntoinePrv
    - elbaro
